version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: awana-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: awana_db
      POSTGRES_USER: awana_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U awana_user -d awana_db"]
      interval: 30s
      timeout: 10s
      retries: 5

  awana:
    image: ghcr.io/joshjetson/awana:latest
    container_name: awana-club
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8083:8080"
    volumes:
      - ./awana_storage:/app/storage
      - ./awana_data:/app/data
    environment:
      - GRAILS_ENV=production
      - DATABASE_URL=jdbc:postgresql://postgres:5432/awana_db
      - DATABASE_USERNAME=awana_user
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  postgres_data: